// an array of all advert categories
const category_map = ["Arts & Entertainment",
                    "Automotive",
                    "Business",
                    "Careers",
                    "Education",
                    "Family & Parenting",
                    "Health & Fitness",
                    "Food & Drink",
                    "Hobbies & Interests",
                    "Home & Garden",
                    "Law, Gov’t & Politics",
                    "News",
                    "Personal Finance",
                    "Society",
                    "Science",
                    "Pets",
                    "Sports",
                    "Style & Fashion",
                    "Technology & Computing",
                    "Travel",
                    "Real Estate",
                    "Shopping",
                    "Religion & Spirituality",
                    "Uncategorized"];

export default category_map;