name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src/server
    
    strategy:
      matrix:
        node-version: [12.x]
   
   # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
        
      - run: npm ci
      - run: npm run build --if-present
      - name: Connect to PostgreSQL and test
        run: npm test
        env:
          # The hostname used to communicate with the PostgreSQL service container
          db_host: localhost
          # The default PostgreSQL port
          db_port: 5432
          db_name: adhunt_test
          db_pass: password
